@uri=http://localhost:8080/api/
@remote_url=https://serler-api-grp5.herokuapp.com/api/

###
POST {{uri}}users
Content-Type: application/json

{
    "email": "solstice2019@126.com",
    "genderId": "5da0a88eadb7840f042e1eb7",
    "name": "zju2014",
    "password": "zju123456"
}

### get roles information
GET {{uri}}roles

### add role information
POST {{uri}}roles
Content-Type: application/json

{
    "name": "User"
}

### get users information

###get genders information
GET {{uri}}genders

###add gender information
POST {{uri}}genders
Content-Type: application/json

{
    "name": "Male"
}